CREATE TABLE `calculation_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`calculationId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`sku` varchar(100),
	`ncmCode` varchar(10) NOT NULL,
	`ncmConfirmed` boolean NOT NULL DEFAULT false,
	`quantity` int NOT NULL,
	`unit` varchar(20) NOT NULL DEFAULT 'UN',
	`unitPriceCents` bigint NOT NULL,
	`totalPriceCents` bigint NOT NULL,
	`unitPriceBrlCents` bigint,
	`totalPriceBrlCents` bigint,
	`iiValueCents` bigint,
	`ipiValueCents` bigint,
	`pisValueCents` bigint,
	`cofinsValueCents` bigint,
	`icmsValueCents` bigint,
	`totalCostCents` bigint,
	`unitCostCents` bigint,
	`suggestedPriceCents` bigint,
	`extractedFromPdf` boolean NOT NULL DEFAULT false,
	`pdfLineReference` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `calculation_items_id` PRIMARY KEY(`id`)
);
