CREATE TABLE `quotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`supplierId` int,
	`quotationNumber` varchar(100),
	`supplierName` varchar(255),
	`supplierCountry` varchar(100),
	`quotationFileUrl` varchar(512),
	`quotationFileKey` varchar(255),
	`quotationFileName` varchar(255),
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`exchangeRate` bigint,
	`originCountry` varchar(100),
	`destinationState` varchar(2) DEFAULT 'SC',
	`isMercosul` boolean NOT NULL DEFAULT false,
	`freightCents` bigint NOT NULL DEFAULT 0,
	`insuranceCents` bigint NOT NULL DEFAULT 0,
	`customsBrokerCents` bigint NOT NULL DEFAULT 0,
	`storageCents` bigint NOT NULL DEFAULT 0,
	`otherCostsCents` bigint NOT NULL DEFAULT 0,
	`totalFobCents` bigint NOT NULL DEFAULT 0,
	`totalCifCents` bigint NOT NULL DEFAULT 0,
	`totalTaxesCents` bigint NOT NULL DEFAULT 0,
	`totalCostCents` bigint NOT NULL DEFAULT 0,
	`totalSuggestedPriceCents` bigint NOT NULL DEFAULT 0,
	`markupPercent` int NOT NULL DEFAULT 3000,
	`status` enum('draft','analyzing','viable','not_viable','negotiating','approved','ordered','shipped','customs','nationalized','completed','cancelled') NOT NULL DEFAULT 'draft',
	`notes` text,
	`aiAnalysis` text,
	`viabilityScore` int,
	`quotationDate` timestamp,
	`validUntil` timestamp,
	`orderDate` timestamp,
	`shipmentDate` timestamp,
	`estimatedArrival` timestamp,
	`customsClearanceDate` timestamp,
	`completionDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotations_id` PRIMARY KEY(`id`)
);
