CREATE TABLE `product_best_prices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`productNameNormalized` varchar(255) NOT NULL,
	`ncmCode` varchar(10),
	`bestPriceBrlCents` bigint NOT NULL,
	`bestPriceSupplierId` int NOT NULL,
	`bestPriceSupplierName` varchar(255) NOT NULL,
	`bestPriceQuotationId` int,
	`bestPriceDate` timestamp NOT NULL,
	`totalSuppliers` int NOT NULL DEFAULT 1,
	`avgPriceBrlCents` bigint,
	`minPriceBrlCents` bigint,
	`maxPriceBrlCents` bigint,
	`savingsPercent` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `product_best_prices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `supplier_prices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`supplierId` int NOT NULL,
	`quotationId` int,
	`calculationId` int,
	`productName` varchar(255) NOT NULL,
	`productNameNormalized` varchar(255) NOT NULL,
	`ncmCode` varchar(10),
	`sku` varchar(100),
	`unitPriceCents` bigint NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`unit` varchar(20) NOT NULL DEFAULT 'UN',
	`unitPriceBrlCents` bigint NOT NULL,
	`exchangeRate` bigint NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`minOrderQuantity` int,
	`leadTimeDays` int,
	`incoterm` varchar(10),
	`paymentTerms` varchar(100),
	`quotationDate` timestamp NOT NULL DEFAULT (now()),
	`validUntil` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplier_prices_id` PRIMARY KEY(`id`)
);
